apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-create-cluster-repo
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: contract_id
      value: "contract_uuid"
    - name: cluster_id
      value: "cluster_uuid"
    - name: template_name
      value: "aws-reference"

  templates:
  - name: createClusterRepo
    activeDeadlineSeconds: 300
    inputs:
      parameters:
      - name: cluster_info
    container:
      name: 'createClusterRepo'
      image: harbor-cicd.taco-cat.xyz/tks/ghcli-alpine:2.0.0
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -ecx
      - |
        function gh_create_repo() {
            echo $TOKEN | gh auth login --with-token

            gh repo create ${USERNAME}/${CLUSTER_ID} --public --confirm
            gh repo create ${USERNAME}/${CLUSTER_ID}-manifests --public --confirm

        }

        function gitea_create_repo() {
            curl -X POST -H "content-type: application/json" -H "Authorization: token ${TOKEN}" --data '{"name": "'${CLUSTER_ID}'"}' $GIT_SVC_HTTP://${GIT_SVC_BASE_URL}/api/v1/orgs/${USERNAME}/repos
            curl -X POST -H "content-type: application/json" -H "Authorization: token ${TOKEN}" --data '{"name": "'${CLUSTER_ID}'-manifests"}' $GIT_SVC_HTTP://${GIT_SVC_BASE_URL}/api/v1/orgs/${USERNAME}/repos
        }

        GIT_SVC_HTTP=${GIT_SVC_URL%://*}
        GIT_SVC_BASE_URL=${GIT_SVC_URL#*//}

        if [ "$GIT_SVC_TYPE" = "gitea" ];then
            gitea_create_repo
        else
            gh_create_repo
        fi

        git clone $GIT_SVC_HTTP://$(echo -n $TOKEN)@${GIT_SVC_BASE_URL}/${USERNAME}/${CONTRACT_ID}.git
        git clone $GIT_SVC_HTTP://$(echo -n $TOKEN)@${GIT_SVC_BASE_URL}/${USERNAME}/${CLUSTER_ID}.git
        git clone $GIT_SVC_HTTP://$(echo -n $TOKEN)@${GIT_SVC_BASE_URL}/${USERNAME}/${CLUSTER_ID}-manifests.git

        cd ${CONTRACT_ID}
        CONTRACT_COMMIT_ID=$(git rev-parse HEAD)
        cd ..

        # Get cluster-api infra provider in the template
        INFRA_PROVIDER="$(cat ${CONTRACT_ID}/$TEMPLATE_NAME/tks-cluster/kustomization.yaml | grep /infra/ | awk -F \/ '{print $3}')"
        echo ${INFRA_PROVIDER} | tee /mnt/out/infra_provider.txt

        if [ "$INFRA_PROVIDER" = "aws" ]; then
            eks_enabled=$(cat ${CONTRACT_ID}/$TEMPLATE_NAME/tks-cluster/site-values.yaml  | grep eksEnabled | awk '{print $2}')
            echo $eks_enabled | tee /mnt/out/managed_cluster.txt
        fi

        cp -r ${CONTRACT_ID}/${TEMPLATE_NAME} ${CLUSTER_ID}/${CLUSTER_ID}

        echo $CLUSTER_INFO

        ## Replace site-values with fetched params ##
        sed -i "s/clusterName:\ cluster.local/clusterName:\ $CLUSTER_ID/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
        case $INFRA_PROVIDER in
          aws)
            ## Fetch cluster params from cluster_info file ##
            val_ssh_key=$(echo $CLUSTER_INFO | sed 's/.*\(ssh_key_name:\ \S*\).*/\1/' | cut -d ':' -f2 | xargs)
            echo "ssh_key_name: $val_ssh_key"
            val_region=$(echo $CLUSTER_INFO | sed 's/.*\(region:\ \S*\).*/\1/' | cut -d ':' -f2 | xargs)
            val_num_of_az=$(echo $CLUSTER_INFO | sed 's/.*\(num_of_az:\ \S*\).*/\1/' | cut -d ':' -f2 | xargs)
            val_machine_type=$(echo $CLUSTER_INFO | sed 's/.*\(machine_type:\ \S*\).*/\1/' | cut -d ':' -f2 | xargs)
            val_min_size=$(echo $CLUSTER_INFO | sed 's/.*\(min_size_per_az:\ \S*\).*/\1/' | cut -d ':' -f2 | xargs)
            val_max_size=$(echo $CLUSTER_INFO | sed 's/.*\(max_size_per_az:\ \S*\).*/\1/' | cut -d ':' -f2 | xargs)
            echo "max_size_per_az: $val_max_size"

            sed -i "s/clusterName:\ cluster.local/clusterName:\ $CLUSTER_ID/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
            sed -i "s/sshKeyName:\ CHANGEME/sshKeyName: $val_ssh_key/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
            sed -i "s/clusterRegion:\ CHANGEME/clusterRegion: $val_region/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
            sed -i "s/awsAccountID:\ CHANGEME/awsAccountID: \"$AWS_ACCOUNT_ID\"/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
            sed -i "s/mdNumOfAz:\ CHANGEME/mdNumOfAz: $val_num_of_az/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
            sed -i "s/mdMinSizePerAz:\ CHANGEME/mdMinSizePerAz: $val_min_size/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
            sed -i "s/mdMaxSizePerAz:\ CHANGEME/mdMaxSizePerAz: $val_max_size/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
            sed -i "s/mdMachineType:\ CHANGEME/mdMachineType: $val_machine_type/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
            sed -i "s/cpReplicas:\ CHANGEME/cpReplicas: 1/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
            ;;

          byoh)
            sed -i "s/clusterName:\ cluster.local/clusterName:\ $CLUSTER_ID/g" $CLUSTER_ID/$CLUSTER_ID/tks-cluster/site-values.yaml
            echo "BYOH"
            ;;

          *)
            echo "Error: wrong infra provider"
            exit 1
            ;;
        esac

        echo "Contract ID: "${CONTRACT_ID} > ${CLUSTER_ID}/META
        echo "Contract Repo Commit: "${CONTRACT_COMMIT_ID} >> ${CLUSTER_ID}/META
        echo "Template Name: "${TEMPLATE_NAME} >> ${CLUSTER_ID}/META

        git config --global user.email "taco_support@sk.com"
        git config --global user.name "SKTelecom TACO"

        cd ${CLUSTER_ID}
        git add *
        git commit -m "add new ${CLUSTER_ID} site"
        git branch -M main
        git remote set-url origin $GIT_SVC_HTTP://$(echo -n $TOKEN)@${GIT_SVC_BASE_URL}/${USERNAME}/${CLUSTER_ID}
        git remote -v
        git push -u origin main
        cd ..

        cd ${CLUSTER_ID}-manifests
        touch README
        git add README
        git commit -m "add new ${CLUSTER_ID} site"
        git branch -M main
        git remote set-url origin $GIT_SVC_HTTP://$(echo -n $TOKEN)@${GIT_SVC_BASE_URL}/${USERNAME}/${CLUSTER_ID}-manifests
        git remote -v
        git push -u origin main
        cd ..

      envFrom:
        - secretRef:
            name: "git-svc-token"
        - secretRef:
            name: "aws-account-id"
      env:
      - name: CONTRACT_ID
        value: "{{workflow.parameters.contract_id}}"
      - name: CLUSTER_ID
        value: "{{workflow.parameters.cluster_id}}"
      - name: TEMPLATE_NAME
        value: "{{workflow.parameters.template_name}}"
      - name: CLUSTER_INFO
        value: "{{inputs.parameters.cluster_info}}"
      volumeMounts:
        - name: out
          mountPath: /mnt/out
    volumes:
      - name: out
        emptyDir: { }
    outputs:
      parameters:
      - name: infra_provider
        valueFrom:
          default: "Something wrong"
          path: /mnt/out/infra_provider.txt
      - name: managed_cluster
        valueFrom:
          default: "Something wrong"
          path: /mnt/out/managed_cluster.txt

  - name: createRepoCredential
    activeDeadlineSeconds: 120
    container:
      name: 'createCredential'
      image: harbor-cicd.taco-cat.xyz/tks/argocd-cli:v2.2.5
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -ecx
      - |
        echo "===== Connect github repo ${USERNAME}/${CLUSTER_ID}-manifests with token ====="
        # log into Argo CD server
        ./argocd login $ARGO_SERVER --plaintext --insecure --username $ARGO_USERNAME \
        --password $ARGO_PASSWORD

        GIT_SVC_HTTP=${GIT_SVC_URL%://*}
        GIT_SVC_BASE_URL=${GIT_SVC_URL#*//}

        ./argocd repo add $GIT_SVC_HTTP://$GIT_SVC_BASE_URL/${USERNAME}/${CLUSTER_ID}-manifests --username ${USERNAME} --password ${TOKEN}
      envFrom:
        - secretRef:
            name: "git-svc-token"
        - secretRef:
            name: "decapod-argocd-config"
      env:
        - name: CLUSTER_ID
          value: "{{workflow.parameters.cluster_id}}"

  - name: main
    inputs:
      parameters:
      - name: cluster_info
    steps:
      - - name: createClusterRepo
          template: createClusterRepo
          arguments:
            parameters:
            - name: cluster_info
              value: "{{inputs.parameters.cluster_info}}"

      - - name: createRepoCredential
          template: createRepoCredential
          arguments: {}

    outputs:
      parameters:
      - name: infra_provider
        valueFrom:
          parameter: "{{steps.createClusterRepo.outputs.parameters.infra_provider}}"
      - name: managed_cluster
        valueFrom:
          parameter: "{{steps.createClusterRepo.outputs.parameters.managed_cluster}}"
