apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-create-contract-repo
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: contract_id
      value: "contract_uuid"
    # Revision for decapod-base and decapod-site repo
    - name: revision
      value: "main"
  templates:
  - name: createContractRepo
    activeDeadlineSeconds: 120
    container:
      name: 'createRepo'
      image: ghcr.io/sktelecom/ghcli-alpine:2.0.0
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -ecx
      - |
        echo $TOKEN | gh auth login --with-token
        echo "===== Current repo list ====="
        gh repo list openinfradev | grep decapod-site
        gh repo list ${USERNAME}

        echo "===== Create and initialize ${USERNAME}/${CONTRACT_ID} site and manifests repositories ====="
        gh repo create ${USERNAME}/${CONTRACT_ID} --public --confirm

        cd ${CONTRACT_ID}
        echo -n ${TOKEN} | gh secret set API_TOKEN_GITHUB

        git clone -b ${REVISION} https://github.com/openinfradev/decapod-site

        cd decapod-site
        echo "Decapod Site Repo Revision: "${REVISION} > META
        echo "Decapod Site Repo Commit: "$(git rev-parse HEAD) >> META

        mv .github _github

        # TODO: support to use decapod-reference-offline later?
        rm -rf decapod-reference
        rm -rf decapod-reference-offline

        # Remove unnecessary app_group directory before commit.
        # If these kinds of apps increases, then they might be defined as black list
        # and then removed by FOR loop iteration.
        # For now, this hardcoding seems enough.
        rm -rf aws-reference/openstack aws-reference/decapod-controller aws-reference/admin-tools
        rm -rf byoh-reference/openstack byoh-reference/decapod-controller byoh-reference/admin-tools

        sed -i "s/BRANCH=\"main\"/BRANCH=\"${REVISION}\"/g" _github/workflows/render-cd.sh

        git config --global user.email "taco_support@sk.com"
        git config --global user.name "SKTelecom TACO"
        git add .
        git commit -m "new contract: ${CONTRACT_ID}"

        git remote add new_contract https://$(echo -n $TOKEN)@github.com/${USERNAME}/${CONTRACT_ID}
        git push new_contract ${REVISION}:main
        cd ..

      envFrom:
        - secretRef:
            name: "git-svc-token"
      env:
        - name: CONTRACT_ID
          value: "{{workflow.parameters.contract_id}}"
        - name: REVISION
          value: "{{workflow.parameters.revision}}"

  - name: main
    steps:
      - - name: createContractRepository
          template: createContractRepo
          arguments: {}

