apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-create-git-svc-token-secret
  namespace: argo
spec:
  entrypoint: createTokenSecret
  arguments:
    parameters:
    - name: user
      value: "git_svc_user"
    - name: token
      value: "git_svc_token"
  templates:
  - name: createTokenSecret
    activeDeadlineSeconds: 120
    container:
      name: 'createClusterSite'
      image: k8s.gcr.io/hyperkube:v1.18.8
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -ecx
      - |
        kubectl delete secret -n argo git-svc-token || true
        kubectl create secret generic git-svc-token --from-literal=USERNAME=${USER} --from-literal=TOKEN=${TOKEN} -n argo
      env:
      - name: USER
        value: "{{workflow.parameters.user}}"
      - name: TOKEN
        value: "{{workflow.parameters.token}}"
