apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-create-git-svc-token-secret
  namespace: argo
spec:
  entrypoint: createTokenSecret
  arguments:
    parameters:
    - name: user
      value: "git_svc_user"
    - name: token
      value: "git_svc_token"
    - name: git_svc_type
      value: "gitea"
    - name: git_svc_url
      value: "http://gitea-http.gitea.svc:3000"
    - name: git_base_branch
      value: "main"
  templates:
  - name: createTokenSecret
    activeDeadlineSeconds: 120
    container:
      name: 'createClusterSite'
      image: harbor.taco-cat.xyz/tks/hyperkube:v1.18.8
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -ecx
      - |
        kubectl delete secret -n argo git-svc-token || true
        kubectl create secret generic git-svc-token \
          --from-literal=USERNAME="{{workflow.parameters.user}}" \
          --from-literal=TOKEN="{{workflow.parameters.token}}" \
          --from-literal=GIT_SVC_TYPE="{{workflow.parameters.git_svc_type}}" \
          --from-literal=GIT_SVC_URL="{{workflow.parameters.git_svc_url}}" \
          --from-literal=GIT_BASE_BRANCH="{{workflow.parameters.git_base_branch}}" \
          -n argo
