apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-delete-cluster-repo
  namespace: argo
spec:
  entrypoint: deleteClusterRepo
  arguments:
    parameters:
    - name: cluster_id
      value: "cluster_uuid"
  templates:
  - name: deleteClusterRepo
    activeDeadlineSeconds: 120
    container:
      name: 'deleteClusterSite'
      image: sktcloud/ghcli:2.5.1
      imagePullPolicy: Always
      command:
      - /bin/bash
      - -ecx
      - |
        echo $TOKEN | gh auth login --with-token

        gh repo delete ${USERNAME}/${CLUSTER_ID} --confirm
        gh repo delete ${USERNAME}/${CLUSTER_ID}-manifests --confirm
      envFrom:
        - secretRef:
            name: "github-tks-mgmt-token"
      env:
      - name: CLUSTER_ID
        value: "{{workflow.parameters.cluster_id}}"
