apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: promote-java-app
  namespace: argo
spec:
  entrypoint: main
  onExit: exit-handler
  arguments:
    parameters:
    - name: target_cluster_id
      value: "C011b88fa"
    - name: app_name
      value: "sample-petclinic"
    - name: namespace
      value: "{{workflow.parameters.app_name}}"
    - name: asa_id
      value: ""
    - name: asa_task_id
      value: ""
    - name: organization_id
      value: "ose4j7p39"
    - name: project_id
      value: ""
    - name: strategy
      value: "blue-green"
    # tks_info service URL
    - name: tks_api_url
      value: "http://tks-api.tks.svc:9110"

  templates:
  - name: exit-handler
    steps:
    - - name: notify-promote-failure
        templateRef:
          name: update-tks-asa-status
          template: updateTksAsaStatus
        arguments:
          parameters:
          - name: organization_id
            value: "{{workflow.parameters.organization_id}}"
          - name: project_id
            value: "{{workflow.parameters.project_id}}"
          - name: asa_id
            value: "{{workflow.parameters.asa_id}}"
          - name: asa_task_id
            value: "{{workflow.parameters.asa_task_id}}"
          - name: status
            value: "PROMOTE_FAILED"
          - name: output
            value: "{{workflow.outputs.parameters.promote_output_global}}"
        when: "{{workflow.status}} != Succeeded"

  - name: main
    steps:
    - - name: notify-promote-start
        templateRef:
          name: update-tks-asa-status
          template: updateTksAsaStatus
        arguments:
          parameters:
          - name: organization_id
            value: "{{workflow.parameters.organization_id}}"
          - name: project_id
            value: "{{workflow.parameters.project_id}}"
          - name: asa_id
            value: "{{workflow.parameters.asa_id}}"
          - name: asa_task_id
            value: "{{workflow.parameters.asa_task_id}}"
          - name: status
            value: "PROMOTING"
          - name: output
            value: ""
    - - name: promote-app
        template: promote-app
    ## Stage for updating preview endpoint to 'N/A'
    ## All other values shouldn't be updated.
    ## (These values for endpoint & helm_revision are discarded by the API)
    - - name: update-endpoint-url
        templateRef:
          name: update-tks-asa-endpoint
          template: updateTksAsaEndpoint
        arguments:
          parameters:
          - name: organization_id
            value: "{{workflow.parameters.organization_id}}"
          - name: project_id
            value: "{{workflow.parameters.project_id}}"
          - name: asa_id
            value: "{{workflow.parameters.asa_id}}"
          - name: asa_task_id
            value: "{{workflow.parameters.asa_task_id}}"
          - name: endpoint
            value: ""
          - name: preview_endpoint
            value: "N/A"
          - name: helm_revision
            value: 0
    - - name: notify-promote-success
        templateRef:
          name: update-tks-asa-status
          template: updateTksAsaStatus
        arguments:
          parameters:
          - name: organization_id
            value: "{{workflow.parameters.organization_id}}"
          - name: project_id
            value: "{{workflow.parameters.project_id}}"
          - name: asa_id
            value: "{{workflow.parameters.asa_id}}"
          - name: asa_task_id
            value: "{{workflow.parameters.asa_task_id}}"
          - name: status
            value: "PROMOTE_SUCCESS"
          - name: output
            value: "{{steps.promote-app.outputs.parameters.promote_output}}"

  #######################
  # Template Definition #
  #######################

  - name: promote-app
    volumes:
    - name: out
      emptyDir: {}
    outputs:
      parameters:
      - name: promote_output
        valueFrom:
          path: /mnt/out/promote_output.log
        globalName: promote_output_global
      # - name: endpoint
      #   valueFrom:
      #     path: /mnt/out/endpoint
    container:
      image: harbor.taco-cat.xyz/tks/appserving-worker:latest
      volumeMounts:
      - name: out
        mountPath: /mnt/out
      command:
      - /bin/sh
      - '-exc'
      - |
        PROMOTE_LOG='/mnt/out/promote_output.log'
        app_name={{workflow.parameters.app_name}}
        strategy={{workflow.parameters.strategy}}

        echo "*workflow name: {{workflow.name}}\n-----" | tee -a $PROMOTE_LOG

        # Prepare kubeconfig
        echo "Preparing kubeconfig for target cluster..." | tee -a $PROMOTE_LOG
        KUBECONFIG_=$(kubectl get secret -n {{workflow.parameters.target_cluster_id}} {{workflow.parameters.target_cluster_id}}-tks-kubeconfig -o jsonpath="{.data.value}" | base64 -d)
        if [[ -z "$KUBECONFIG_" ]]; then
          echo "Couldn't get kubeconfig for cluster {{workflow.parameters.target_cluster_id}}" | tee -a $PROMOTE_LOG
          exit 1
        fi

        echo "$KUBECONFIG_" > /etc/kubeconfig_temp
        chmod 0600 /etc/kubeconfig_temp
        export KUBECONFIG='/etc/kubeconfig_temp'



        #==========================================================
        # function: check_rollout_phase (Healthy)
        #==========================================================
        function check_rollout_phase() {
          # check if abort is completed
          rollout_phase=$1
          rollout_status=$2
          app_name={{workflow.parameters.app_name}}
          promote_done=false
          for i in `seq 1 10`
          do
            phase=$(kubectl get rollout ${app_name} -n {{workflow.parameters.namespace}} -o jsonpath='{.status.phase}')
            ro_stat=$(kubectl argo rollouts status ${app_name} -n {{workflow.parameters.namespace}} --timeout 2s | cut -d' ' -f1 || true)

            if [ "$phase" == "$rollout_phase" ] && [ "$ro_stat" == "$rollout_status" ]; then
              echo "'Promote' request completed successfully." | tee -a $PROMOTE_LOG
              promote_done=true
              break
            else
              echo "Waiting for 'promote' to be done.. sleeping 3 secs.."
              sleep 3
            fi
          done

          if [ "$promote_done" = false ]; then
            echo "Timed out waiting for 'promote' to be done.." | tee -a $ABORT_LOG
            exit 1
          fi
        }



        #==========================================================
        # function: check_rollout_replicas
        #==========================================================
        function check_rollout_replicas() {
          # Check num of replicas
          ready=false
          SLEEP_INTERVAL=5
          for i in `seq 1 15`
          do
            replicas=$(kubectl get rollout/{{workflow.parameters.app_name}} -n {{workflow.parameters.namespace}} -o jsonpath='{.status.replicas}')
            available_repls=$(kubectl get rollout/{{workflow.parameters.app_name}} -n {{workflow.parameters.namespace}} -o jsonpath='{.status.availableReplicas}')

            if [ -z "$replicas" ]; then
              echo "Failed to get number of replicas. Exiting workflow.." | tee -a $DEPLOY_LOG
              exit 1
            fi

            # check if replicas == availableReplicas
            if [ "$replicas" == "$available_repls" ]; then
              echo "All replicas are available. Promote is successful!" | tee -a $DEPLOY_LOG
              ready=true
              break
            fi
            sleep $SLEEP_INTERVAL
          done  # End of FOR loop #

          if [ "$ready" = false ]; then
            echo "Timed out waiting for promote to be done.." | tee -a $DEPLOY_LOG
            exit 1
          fi
        }



        #==========================================================
        # Write revision (latest deployed version)
        #==========================================================
        function write_revision() {
          # Writing helm release info to file.
          revision=$( (helm history {{workflow.parameters.app_name}} --kubeconfig /etc/kubeconfig_temp -n {{workflow.parameters.namespace}} | grep deployed | cut -d' ' -f1) 2> >(tee -a $PROMOTE_LOG >&2) )
          
          # Cmds with pipe doesn't catch correct exit code, so we need to check it somehow.
          if [ -z "$revision" ]; then
            echo "Failed to get helm release revision. Exiting workflow.." | tee -a $PROMOTE_LOG
            exit 1
          fi

          # Debug revision number
          echo "Deployed revision number: $revision"
          echo $revision > /mnt/out/revision
        }


        #==========================================================
        # Start promoting Rollout
        #==========================================================
        echo "Starting promote..." | tee -a $PROMOTE_LOG

        # Check if rollout is waiting for promotion
        if (kubectl argo rollouts status ${app_name} -n {{workflow.parameters.namespace}} --timeout 2s | grep Paused); then
          echo "Rollout is in Paused state. Starting promote process.." | tee -a $PROMOTE_LOG
        else
          echo "Error: Rollout is NOT in Paused state. Exiting.." | tee -a $PROMOTE_LOG
          exit 1
        fi

        # Perform promotion
        kubectl argo rollouts promote ${app_name} -n {{workflow.parameters.namespace}}


        #==========================================================
        # check promote finished (Healthy)
        #==========================================================
        check_rollout_phase "Healthy" "Healthy"
        


        #==========================================================
        # check replicas
        #==========================================================
        check_rollout_replicas

