apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cp-aws-infrastructure
  namespace: argo
spec:
  entrypoint: CreateAwsELB
  arguments:
    parameters:
    - name: cluster_id
      value: "C1eee74fd"
      
  volumes:
  - name: config
    secret:
      secretName: tks-admin-kubeconfig-secret
      namespace: argo
  - name: artifacts
    configMap:
      name: aws-artifacts
      namespace: argo
      defaultMode: 0555
  templates:
  - name: CreateAwsELB
    activeDeadlineSeconds: 1800
    container:
      image: harbor-cicd.taco-cat.xyz/tks/python_kubectl_helm_argo:v1.0.1
      command:
      - /bin/bash
      - -exc
      - |
        mkdir ~/.kube
        cp /kube/value ~/.kube/config
        while [ $(kubectl get awscluster -n argo $cluster_id -o jsonpath="{.spec.network.vpc.id}" | wc -c ) == 0 ]; do
          echo "> Wait for checking the VPC ID"
          sleep 2
        done
        vpc_id=$(kubectl get awscluster -n argo $cluster_id -o jsonpath="{.spec.network.vpc.id}")
        lbname=${cluster_id}-lb

        cat <<EOF >/$cluster_id.yaml
        ## securitygroup.yaml
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        metadata:
          name: $lbname-sg
          labels:
            lb: $lbname
        spec:
          deletionPolicy: Delete
          forProvider:
            region: ap-northeast-2
            vpcId: $vpc_id
            groupName: $lbname-sg
            description: Security group for LB of Ingress Controller in $cluster_id
            egress:
            - ipProtocol: "-1"
              ipRanges:
              - cidrIp: 0.0.0.0/0
            ingress:
            - fromPort: 80
              toPort: 80
              ipProtocol: tcp
              ipRanges:
              - cidrIp: 0.0.0.0/0
            - fromPort: 443
              toPort: 443
              ipProtocol: tcp
              ipRanges:
              - cidrIp: 0.0.0.0/0
            tags:
            - key: creator
              value: crossplane-taco
          providerConfigRef:
            name: awsconfig
        EOF

        cat /$cluster_id.yaml
        kubectl apply -f /$cluster_id.yaml

        kubectl wait --for=condition=ready --timeout=300s -n d1 securitygroup/$lbname-sg

        cat <<EOF >/$cluster_id.yaml
        ## elb.yaml
        apiVersion: elasticloadbalancing.aws.crossplane.io/v1alpha1
        kind: ELB
        metadata:
          name: $lbname
          labels:
            lb: $lbname
        spec:
          deletionPolicy: Delete
          forProvider:
            region: ap-northeast-2
            securityGroupIdRefs:
            - name: $lbname-sg
            subnetIds: 
        EOF
        for subnet in $(/artifacts/cpgetPublicSubnet.py $cluster_id )
        do
          echo "    - $subnet" >>/$cluster_id.yaml
        done

        cat <<EOF >>/$cluster_id.yaml
            listeners:
            - instancePort: 32080
              instanceProtocol: tcp
              loadBalancerPort: 80
              protocol: tcp
            - instancePort: 32443
              instanceProtocol: tcp
              loadBalancerPort: 443
              protocol: tcp
            healthCheck:
              target: HTTP:32081/healthz
              timeout: 5
              interval: 30
              unhealthyThreshold: 6
              healthyThreshold: 3
            tags:
            - key: creator
              value: crossplane-taco
          providerConfigRef:
            name: awsconfig
        EOF

        cat  /$cluster_id.yaml

        for instance in $(/artifacts/cpgetWorkerInstances.py $cluster_id )
        do
          cat <<EOF >>/$cluster_id.yaml
        ## elbattachment.yaml
        ---
        apiVersion: elasticloadbalancing.aws.crossplane.io/v1alpha1
        kind: ELBAttachment
        metadata:
          name: instance-$instance
          labels:
            lb: $lbname
        spec:
          deletionPolicy: Delete
          forProvider:
            region: ap-northeast-2
            elbNameRef:
              name: $lbname
            instanceId: $instance
          providerConfigRef:
            name: awsconfig
        EOF

        done

        cat /$cluster_id.yaml
        kubectl apply -f /$cluster_id.yaml
        kubectl wait --for=condition=ready --timeout=300s -n d1 elb/$lbname

      envFrom:
      - secretRef:
          name: "decapod-argocd-config"
      env:
      - name: cluster_id
        value: "{{workflow.parameters.cluster_id}}"
      volumeMounts:
      - name: config
        mountPath: "/kube"
      - name: artifacts
        mountPath: "/artifacts"

  - name: DeleteAwsELB
    activeDeadlineSeconds: 1800
    container:
      image: harbor-cicd.taco-cat.xyz/tks/python_kubectl_helm_argo:v1.0.1
      command:
      - /bin/bash
      - -exc
      - |
        mkdir ~/.kube
        cp /kube/value ~/.kube/config
        lbname=${cluster_id}-lb
        kubectl delete ResourceRecordSet --selector=lb=$lbname
        kubectl delete ELBAttachment --selector=lb=$lbname
        kubectl delete ELB --selector=lb=$lbname
        kubectl delete SecurityGroup --selector=lb=$lbname
      env:
      - name: cluster_id
        value: "{{workflow.parameters.cluster_id}}"
      volumeMounts:
      - name: config
        mountPath: "/kube"
      - name: artifacts
        mountPath: "/artifacts"

  - name: RegisterTACOapp2route53
    activeDeadlineSeconds: 1800
    container:
      image: harbor-cicd.taco-cat.xyz/tks/python_kubectl_helm_argo:v1.0.1
      command:
      - /bin/bash
      - -exc
      - |
        mkdir ~/.kube
        cp /kube/value ~/.kube/config

        lbname=${cluster_id}-lb
        elbdns=$(kubectl get elb $lbname -o jsonpath="{.status.atProvider.dnsName}")

        for application in kibana grafana kiali
        do
          cat <<EOF >/$application.yaml
          apiVersion: route53.aws.crossplane.io/v1alpha1
          kind: ResourceRecordSet
          metadata:
            annotations:
              crossplane.io/external-name: $application-${cluster_id}.taco-cat.xyz
            name: $application-${cluster_id}
            labels:
              lb: $lbname
          spec:
            deletionPolicy: Delete
            forProvider:
              resourceRecords:
              - value: $elbdns
              ttl: 300
              type: CNAME
              zoneId:  Z104697219C1N0592X9B3 
            providerConfigRef:
              name: awsconfig
        EOF
          kubectl apply -f /$application.yaml
        done

      envFrom:
      - secretRef:
          name: "decapod-argocd-config"
      env:
      - name: cluster_id
        value: "{{workflow.parameters.cluster_id}}"

      volumeMounts:
      - name: config
        mountPath: "/kube"
