FROM harbor-cicd.taco-cat.xyz/tks/python-centos-wf-worker:v2.0 AS base
USER root

RUN yum install -y epel-release
RUN yum install -y jq
RUN pip3 install requests

COPY tks /usr/local/bin/tks

#docker build -t harbor-cicd.taco-cat.xyz/tks/tks-api:v1.0 -f Dockerfile.tks-api .
