FROM docker:20.10.16-git

MAINTAINER Cloud Co, SK Telecom

USER root

RUN apk add --no-cache curl

# Install kubectl
RUN curl -Lo /usr/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x /usr/bin/kubectl

CMD ["sh"]
