FROM centos:centos7

MAINTAINER Cloud Co, SK Telecom

USER root
RUN curl -sSLo sonobuoy.tar.gz https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.56.6/sonobuoy_0.56.6_linux_amd64.tar.gz
RUN tar -xzf ./sonobuoy.tar.gz
RUN chmod +x ./sonobuoy && cp sonobuoy /usr/bin/ && rm -rf ./sonobuoy*

RUN curl -Lo /usr/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN chmod +x /usr/bin/kubectl

CMD ["bash"]
