apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-remove-lma-federation
  namespace: argo
spec:
  entrypoint: removeLMA
  arguments:
    parameters:
    - name: app_group
      value: "lma"
    - name: github_account
      value: "tks-management"
    - name: tks_info_host
      value: "tks-info.tks.svc"
    - name: cluster_id
      value: "Cabbead61"
    - name: app_group_id
      value: "Aabbead61"
    ##########################
    # For removeLMA task #
    ##########################
    - name: app_prefix
      value: "{{workflow.parameters.cluster_id}}"
    - name: filter
      value: "app={{workflow.parameters.cluster_id}}-{{workflow.parameters.app_group}}"
  volumes:
  - name: tks-proto-vol
    configMap:
      name: tks-proto
  templates:
  - name: removeLMA
    steps:
    - - name: GetMyThanosScEndpoint
        templateRef:
          name: tks-lma-federation
          template: GetMyThanosScEndpoint
        arguments:
          parameters:
          - name: target_namespace
            value: lma

    - - name: removeAppGroup
        templateRef:
          name: remove-lma-federation
          template: process

    - - name: deleteNamespace
        template: deleteNamespace
        arguments:
          parameters:
            - name: target_namespace
              value: "lma"

    # TODO: Is this still necessary?
    - - name: updateTksInfo
        templateRef:
          name: delete-tks-app-group-info
          template: deleteTksAppGroup
     
      # LMA appGroup specific task #
    - - name: collectClusterList
        template: collectClusterList
        arguments:
          # These params should be moved to global argument? #
          parameters:
          - name: tks_info_host
            value:  "{{ workflow.parameters.tks_info_host }}"
          - name: app_group_id
            value: "{{ workflow.parameters.app_group_id }}"

    # Delete endpoint from other cluster's manifests
    - - name: updateDecapodManifestOutwards
        templateRef:
          name: update-decapod-manifest
          template: updateManifest
        arguments:
          parameters:
          - name: site_repo_url
            value: "github.com/{{workflow.parameters.github_account}}/{{item.name}}"
          - name: action
            value: "delete"
          - name: cluster_name
            value: "{{item.name}}"
          - name: app_group
            value: "{{workflow.parameters.app_group}}"
          - name: chart
            value: "thanos"
          - name: kv_map_str 
            value: "{'querier.stores': '{{steps.GetMyThanosScEndpoint.outputs.parameters.my_thanos_sc_ep}}'}"
        withParam: "{{steps.collectClusterList.outputs.parameters.outwards_cluster_list}}"

  #######################
  # Template Definition #
  #######################
  - name: deleteNamespace
    inputs:
      parameters:
        - name: target_namespace
    container:
      name: delete-namespace
      image: k8s.gcr.io/hyperkube:v1.18.6
      command:
        - /bin/bash
        - '-c'
        - |
          function log() {
            level=$1
            msg=$2
            date=$(date '+%F %H:%M:%S')
            echo "[$date] $level     $msg"
          }

          kube_params=""

          if [[ -n "{{workflow.parameters.cluster_id}}" ]]; then
            kube_secret=$(kubectl get secret -n {{workflow.parameters.cluster_id}} {{workflow.parameters.cluster_id}}-kubeconfig -o jsonpath="{.data.value}" | base64 -d)
            echo -e "kube_secret:\n$kube_secret" | head -n 5
            cat <<< "$kube_secret" > /etc/kubeconfig

            kube_params+="--kubeconfig=/etc/kubeconfig"
          fi

          kubectl $kube_params get ns ${TARGET_NAMESPACE}
          if [[ $? =~ 0 ]]; then
            kubectl $kube_params delete ns ${TARGET_NAMESPACE}
            log "INFO" "${TARGET_NAMESPACE} was successfully deleted."
          fi
      env:
        - name: TARGET_NAMESPACE
          value: '{{inputs.parameters.target_namespace}}'
    activeDeadlineSeconds: 900
    retryStrategy:
      limit: 2

  - name: collectClusterList
    inputs:
      parameters:
      - name: tks_info_host
      - name: app_group_id
    outputs:
      parameters:
      - name: outwards_cluster_list
        valueFrom:
          path: /mnt/out/cluster_list.txt
    volumes:
    - name: out
      emptyDir: {}
    script: 
      name: 'collect'
      image: sktcloud/python-centos-wf-worker:v2.0
      command:
      - python
      envFrom:
      - secretRef:
          name: "git-svc-token"
      env:
      - name: PYTHONPATH
        value: "/opt/protobuf/:/opt/rh/rh-python38/root/lib/python3.8/site-packages/:/opt/app-root/lib/python3.8/site-packages/"
      volumeMounts:
      - name: tks-proto-vol
        mountPath: "/opt/protobuf"
        readOnly: true
      - name: out
        mountPath: /mnt/out
      source: |
        import sys
        import os
        import google.protobuf
        import grpc
        import info_pb2
        import info_pb2_grpc
        import common_pb2
        import common_pb2_grpc
        import json
        import git

        output_cluster_list = []
        temp_map = {}
        outwards_endpoint_map = {}

        ip = "{{inputs.parameters.tks_info_host}}"
        # TODO: Make port workflow param?
        port = 9110
        addr = "%s:%d" % (ip, port)
        print("tks-info addr: %s" % addr)

        with grpc.insecure_channel(addr) as channel:
            cl_stub = info_pb2_grpc.ClusterInfoServiceStub(channel)
            app_stub = info_pb2_grpc.AppInfoServiceStub(channel)

            res = cl_stub.GetCluster(info_pb2.GetClusterRequest(cluster_id="{{workflow.parameters.cluster_id}}"))

            print("Response from GetCluster: ")
            print(res.cluster)
            contract_id = res.cluster.contract_id
            csp_id = res.cluster.csp_id
            cur_cluster_name = res.cluster.id

            res = cl_stub.GetClusters(info_pb2.GetClustersRequest(contract_id=contract_id, csp_id=''))

            print("Iterating over clusters in the same contract...")

            # Iterate over cluster list except current cluster #
            for cluster in res.clusters:
                if cluster.id != "{{workflow.parameters.cluster_id}}":
                  print("*******************************************")
                  print("Checking cluster: {}".format(cluster.id))

                  print("Checking if corresponding cluster repo exists..")
                  url = "@github.com/{{workflow.parameters.github_account}}/{}".format(cluster.id)
                  repoUrl = "https://" + os.environ['TOKEN'] + url
                  try:
                    repo = git.Repo.clone_from(repoUrl, './tempcluster')

                  except git.exc.GitCommandError as e:
                    print(e)
                    print("Repo {} doesn't exist. Skipping this cluster..".format(repoUrl))
                    continue

                  res = app_stub.GetAppGroupsByClusterID(common_pb2.IDRequest(id=cluster.id))
                  print("Response from GetAppGroupsByClusterID:")
                  print(res.app_groups)

                  os.system("rm -rf ./tempcluster")

                  # Check if LMA group exists.
                  for app_group in res.app_groups:
                    if app_group.type == common_pb2.LMA:
                      print("Found LMA app_group: {}".format(app_group.app_group_name))
                      res = app_stub.GetApps(info_pb2.GetAppsRequest(app_group_id=app_group.app_group_id, type=common_pb2.PROMETHEUS))

                      # Add this cluster to outward list so that current ep is deleted from this cluster
                      temp_map["name"] = cluster.id
                      str_json = json.dumps(temp_map)
                      output_cluster_list.append(str_json)

        ###########################
        # Construct output params #
        ###########################
        len_list = len(output_cluster_list)

        with open("/mnt/out/cluster_list.txt", "w") as f:
          f.write('[')

          print("*** Outwards Cluster List ***")
          for idx, item in enumerate(output_cluster_list, start=1):
            print("item {}: {}".format(idx, item))
            f.write(item.strip("'"))
            if idx < len_list:
              f.write(',')
          f.write(']')
