apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-lma-federation
  namespace: argo
spec:
  entrypoint: deployLMA
  arguments:
    parameters:
    - name: site_name
      value: "decapod-refrence"
    - name: logging_component
      value: "efk"
    - name: github_account
      value: "tks-management"
    - name: manifest_repo_url
      value: "https://github.com/openinfradev/decapod-manifests"
    - name: revision
      value: "main"
    - name: app_prefix
      value: "{{workflow.parameters.site_name}}"
    ##########################
    # For tks-info task #
    ##########################
    - name: tks_info_host
      value: "tks-info.tks.svc"
    - name: cluster_id
      value: "Cabbead61"
    - name: app_group_id
      value: "Aabbead61"
  volumes:
  - name: tks-proto-vol
    configMap:
      name: tks-proto
  templates:
  - name: deployLMA
    steps:
    - - name: createNamespace
        template: createNamespace
        arguments:
          parameters:
            - name: target_namespace
              value: lma

    - - name: installApps
        templateRef:
          name: lma-federation
          template: deploy

    - - name: GetMyThanosScEndpoint
        template: GetMyThanosScEndpoint
        arguments:
          parameters:
          - name: target_namespace
            value: lma

    - - name: updateEndpointToTksInfo
        templateRef:
          name: update-tks-app-group-info
          template: updateTksAppGroup
        arguments:
          parameters:
          - name: endpoints
            value: "{'PROMETHEUS': '{{steps.GetMyThanosScEndpoint.outputs.parameters.my_thanos_sc_ep}}'}"

      # LMA appGroup specific task #
    - - name: collectThanosScEndpoints
        template: collectThanosScEndpoints
        arguments:
          # These params should be moved to global argument? #
          parameters:
          - name: tks_info_host
            value:  "{{ workflow.parameters.tks_info_host }}"
          - name: app_group_id
            value: "{{ workflow.parameters.app_group_id }}"

    - - name: updateDecapodManifestOutwards
        templateRef:
          name: update-decapod-manifest
          template: updateManifest
        arguments:
          parameters:
          - name: site_repo_url
            value: "github.com/{{workflow.parameters.github_account}}/{{item.name}}"
          - name: action
            value: "insert"
          - name: cluster_name
            value: "{{item.name}}"
          - name: app_group
            value: "lma"
          - name: chart
            value: "thanos"
          - name: kv_map_str 
            value: "{'querier.stores': '{{steps.GetMyThanosScEndpoint.outputs.parameters.my_thanos_sc_ep}}'}"
        withParam: "{{steps.collectThanosScEndpoints.outputs.parameters.outwards_cluster_list}}"

    - - name: updateDecapodManifestInwards
        templateRef:
          name: update-decapod-manifest
          template: updateManifest
        arguments:
          parameters:
          - name: site_repo_url
            value: "github.com/{{workflow.parameters.github_account}}/{{workflow.parameters.cluster_id}}"
          - name: action
            value: "insert"
          # TODO: modify this to reflect actual cluster name for all cases
          # instead of just using cluster id
          - name: cluster_name
            value: "{{steps.collectThanosScEndpoints.outputs.parameters.cur_cluster_name}}"
          - name: app_group
            value: "lma"
          - name: chart
            value: "thanos"
          ## {"querier.stores": ['endpointA', 'endpointB']}
          - name: kv_map_str
            value: "{{steps.collectThanosScEndpoints.outputs.parameters.inwards_endpoint_map}}"

  #######################
  # Template Definition #
  #######################
  - name: createNamespace
    inputs:
      parameters:
        - name: target_namespace
    container:
      name: create-namespace
      image: harbor-cicd.taco-cat.xyz/tks/hyperkube:v1.18.6
      command:
        - /bin/bash
        - '-c'
        - |
          function log() {
            level=$1
            msg=$2
            date=$(date '+%F %H:%M:%S')
            echo "[$date] $level     $msg"
          }

          kube_secret=$(kubectl get secret -n {{workflow.parameters.cluster_id}} {{workflow.parameters.cluster_id}}-kubeconfig -o jsonpath="{.data.value}" | base64 -d)
          echo -e "kube_secret:\n$kube_secret" | head -n 5
          cat <<< "$kube_secret" > /etc/kubeconfig

          kubectl --kubeconfig=/etc/kubeconfig get ns ${TARGET_NAMESPACE}
          if [[ $? =~ 1 ]]; then
            kubectl --kubeconfig=/etc/kubeconfig create ns ${TARGET_NAMESPACE}
            kubectl --kubeconfig=/etc/kubeconfig label ns ${TARGET_NAMESPACE} name=${TARGET_NAMESPACE}
            kubectl --kubeconfig=/etc/kubeconfig label ns ${TARGET_NAMESPACE} taco-tls=enabled
            log "INFO" "${TARGET_NAMESPACE} successfully created."
          fi
      env:
        - name: TARGET_NAMESPACE
          value: '{{inputs.parameters.target_namespace}}'
    activeDeadlineSeconds: 900
    retryStrategy:
      limit: 2

  - name: GetMyThanosScEndpoint
    inputs:
      parameters:
      - name: target_namespace
    outputs:
      parameters:
      - name: my_thanos_sc_ep
        valueFrom:
          path: /mnt/out/thanos_sc_ep.txt
    volumes:
    - name: out
      emptyDir: {}
    container:
      name: 'get-thanos-ep'
      image: harbor-cicd.taco-cat.xyz/tks/hyperkube:v1.18.6
      envFrom:
      - secretRef:
          name: "git-svc-token"
      env:
        - name: TARGET_NAMESPACE
          value: '{{inputs.parameters.target_namespace}}'
      volumeMounts:
      - name: out
        mountPath: /mnt/out
      command:
        - /bin/bash
        - '-c'
        - |
          kube_secret=$(kubectl get secret -n {{workflow.parameters.cluster_id}} {{workflow.parameters.cluster_id}}-kubeconfig -o jsonpath="{.data.value}" | base64 -d)
          echo -e "kube_secret:\n$kube_secret" | head -n 5
          cat <<< "$kube_secret" > /etc/kubeconfig

          THANOS_SC_PORT='10901'
          THANOS_SC_SVC='lma-thanos-external'
          thanos_sc_ep=$(kubectl --kubeconfig=/etc/kubeconfig get svc ${THANOS_SC_SVC} -n ${TARGET_NAMESPACE} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          if [[ -z "$thanos_sc_ep" ]]; then
            echo "Error: could not retrieve thanos sidecar endpoint from service resource."
            exit 1
          else
            echo "$thanos_sc_ep:$THANOS_SC_PORT" > /mnt/out/thanos_sc_ep.txt
          fi


  - name: collectThanosScEndpoints
    inputs:
      parameters:
      - name: tks_info_host
      - name: app_group_id
    outputs:
      parameters:
      - name: outwards_cluster_list
        valueFrom:
          path: /mnt/out/cluster_list.txt
      - name: inwards_endpoint_map
        valueFrom:
          path: /mnt/out/inwards_endpoint.txt
      - name: cur_cluster_name
        valueFrom:
          path: /mnt/out/cur_cluster_name.txt
    volumes:
    - name: out
      emptyDir: {}
    script: 
      name: 'collect'
      image: harbor-cicd.taco-cat.xyz/tks/python-centos-wf-worker:v2.0
      command:
      - python
      envFrom:
      - secretRef:
          name: "git-svc-token"
      env:
      - name: PYTHONPATH
        value: "/opt/protobuf/:/opt/rh/rh-python38/root/lib/python3.8/site-packages/:/opt/app-root/lib/python3.8/site-packages/"
      volumeMounts:
      - name: tks-proto-vol
        mountPath: "/opt/protobuf"
        readOnly: true
      - name: out
        mountPath: /mnt/out
      source: |
        import sys
        import os
        import google.protobuf
        import grpc
        import info_pb2
        import info_pb2_grpc
        import common_pb2
        import common_pb2_grpc
        import json
        import git

        output_cluster_list = []
        temp_map = {}
        inwards_endpoint_list = []
        inwards_endpoint_map = {}
        outwards_endpoint_map = {}

        ip = "{{inputs.parameters.tks_info_host}}"
        # TODO: Make port workflow param?
        port = 9110
        addr = "%s:%d" % (ip, port)
        print("tks-info addr: %s" % addr)

        with grpc.insecure_channel(addr) as channel:
            cl_stub = info_pb2_grpc.ClusterInfoServiceStub(channel)
            app_stub = info_pb2_grpc.AppInfoServiceStub(channel)

            res = cl_stub.GetCluster(info_pb2.GetClusterRequest(cluster_id="{{workflow.parameters.cluster_id}}"))

            print("Response from GetCluster: ")
            print(res.cluster)
            contract_id = res.cluster.contract_id
            csp_id = res.cluster.csp_id
            cur_cluster_name = res.cluster.id

            res = cl_stub.GetClusters(info_pb2.GetClustersRequest(contract_id=contract_id, csp_id=''))

            print("Iterating over clusters in the same contract...")

            # Iterate over cluster list except current cluster #
            for cluster in res.clusters:
                if cluster.status != common_pb2.RUNNING:
                  continue

                if cluster.id != "{{workflow.parameters.cluster_id}}":
                  print("*******************************************")
                  print("Checking cluster: {}".format(cluster.id))

                  print("Checking if corresponding cluster repo exists..")
                  url = "@github.com/{{workflow.parameters.github_account}}/{}".format(cluster.id)
                  repoUrl = "https://" + os.environ['TOKEN'] + url
                  try:
                    repo = git.Repo.clone_from(repoUrl, './tempcluster')

                  except git.exc.GitCommandError as e:
                    print(e)
                    print("Repo {} doesn't exist. Skipping this cluster..".format(repoUrl))
                    continue

                  res = app_stub.GetAppGroupsByClusterID(common_pb2.IDRequest(id=cluster.id))
                  print("Response from GetAppGroupsByClusterID:")
                  print(res.app_groups)

                  os.system("rm -rf ./tempcluster")

                  # Check if LMA group exists.
                  for app_group in res.app_groups:
                    if app_group.type == common_pb2.LMA:
                      print("Found LMA app_group: {}".format(app_group.app_group_name))
                      res = app_stub.GetApps(info_pb2.GetAppsRequest(app_group_id=app_group.app_group_id, type=common_pb2.PROMETHEUS))

                      if res.apps:
                        # This is based on the premise that there's only one prometheus per appGroup.
                        endpoint = res.apps[0].endpoint
                        print("Get Thanos-sc endpoint: {}. Appending it to inward list.".format(endpoint))

                        # Add this cluster's endpoint to endpoint map
                        inwards_endpoint_list.append(endpoint)

                        # Add this cluster to outward list so that current ep is updated to this cluster
                        temp_map["name"] = cluster.id
                        str_json = json.dumps(temp_map)
                        output_cluster_list.append(str_json)

        # Compose profer format to be used as input on next step 
        inwards_endpoint_map['querier.stores'] = inwards_endpoint_list

        ###########################
        # Construct output params #
        ###########################
        len_list = len(output_cluster_list)

        with open("/mnt/out/cluster_list.txt", "w") as f:
          f.write('[')

          print("*** Outwards Cluster List ***")
          for idx, item in enumerate(output_cluster_list, start=1):
            print("item {}: {}".format(idx, item))
            f.write(item.strip("'"))
            if idx < len_list:
              f.write(',')
          f.write(']')

        with open("/mnt/out/inwards_endpoint.txt", "w") as f:
          str_inwards_endpoint = repr(inwards_endpoint_map)
          f.write(str_inwards_endpoint)

        with open("/mnt/out/cur_cluster_name.txt", "w") as f:
          f.write(cur_cluster_name)
